services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "8080:80"   # TODO: 8080 -> 443 in vm 
    volumes:
      - ../web:/var/www/html
      # - ../certs:/etc/nginx/
    networks:
      - inception
  wordpress:
    env_file:
      - .env
    build: requirements/wordpress
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ../web:/var/www/html
    networks:
      - inception
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - ../database:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  inception_database:
    driver: local
  # inception_web:
  #   driver: local
  # inception_certs:
  #   driver: local

